/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as MainTabelaRouteImport } from './routes/_main/tabela'
import { Route as MainRankingRouteImport } from './routes/_main/ranking'
import { Route as MainPerfilRouteImport } from './routes/_main/perfil'
import { Route as MainHomeRouteImport } from './routes/_main/home'
import { Route as MainGruposRouteImport } from './routes/_main/grupos'
import { Route as MainChaveamentoRouteImport } from './routes/_main/chaveamento'
import { Route as MainCarteiraRouteImport } from './routes/_main/carteira'
import { Route as MainAjudaRouteImport } from './routes/_main/ajuda'
import { Route as MainAdminRouteImport } from './routes/_main/admin'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin.index'
import { Route as MainAdminUsuariosRouteImport } from './routes/_main/admin.usuarios'
import { Route as MainAdminSyncRouteImport } from './routes/_main/admin.sync'
import { Route as MainAdminSaquesRouteImport } from './routes/_main/admin.saques'
import { Route as MainAdminRelatoriosRouteImport } from './routes/_main/admin.relatorios'
import { Route as MainAdminPartidasRouteImport } from './routes/_main/admin.partidas'
import { Route as MainAdminNotificacoesRouteImport } from './routes/_main/admin.notificacoes'
import { Route as MainAdminDepositosRouteImport } from './routes/_main/admin.depositos'
import { Route as MainAdminCustodiaRouteImport } from './routes/_main/admin.custodia'
import { Route as MainAdminConvitesRouteImport } from './routes/_main/admin.convites'
import { Route as MainAdminConfiguracoesRouteImport } from './routes/_main/admin.configuracoes'
import { Route as MainAdminChecklistRouteImport } from './routes/_main/admin.checklist'
import { Route as MainAdminAuditoriaRouteImport } from './routes/_main/admin.auditoria'
import { Route as MainAdminApostasRouteImport } from './routes/_main/admin.apostas'
import { Route as ApiPublicHooksSyncPartidasRouteImport } from './routes/api/public/hooks/sync-partidas'
import { Route as MainAdminUsuariosIdRouteImport } from './routes/_main/admin.usuarios.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTabelaRoute = MainTabelaRouteImport.update({
  id: '/tabela',
  path: '/tabela',
  getParentRoute: () => MainRoute,
} as any)
const MainRankingRoute = MainRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => MainRoute,
} as any)
const MainPerfilRoute = MainPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainGruposRoute = MainGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => MainRoute,
} as any)
const MainChaveamentoRoute = MainChaveamentoRouteImport.update({
  id: '/chaveamento',
  path: '/chaveamento',
  getParentRoute: () => MainRoute,
} as any)
const MainCarteiraRoute = MainCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => MainRoute,
} as any)
const MainAjudaRoute = MainAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminUsuariosRoute = MainAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminSyncRoute = MainAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminSaquesRoute = MainAdminSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminRelatoriosRoute = MainAdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminPartidasRoute = MainAdminPartidasRouteImport.update({
  id: '/partidas',
  path: '/partidas',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminNotificacoesRoute = MainAdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminDepositosRoute = MainAdminDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminCustodiaRoute = MainAdminCustodiaRouteImport.update({
  id: '/custodia',
  path: '/custodia',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminConvitesRoute = MainAdminConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminConfiguracoesRoute = MainAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminChecklistRoute = MainAdminChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminAuditoriaRoute = MainAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminApostasRoute = MainAdminApostasRouteImport.update({
  id: '/apostas',
  path: '/apostas',
  getParentRoute: () => MainAdminRoute,
} as any)
const ApiPublicHooksSyncPartidasRoute =
  ApiPublicHooksSyncPartidasRouteImport.update({
    id: '/api/public/hooks/sync-partidas',
    path: '/api/public/hooks/sync-partidas',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainAdminUsuariosIdRoute = MainAdminUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainAdminUsuariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof MainAdminRouteWithChildren
  '/ajuda': typeof MainAjudaRoute
  '/carteira': typeof MainCarteiraRoute
  '/chaveamento': typeof MainChaveamentoRoute
  '/grupos': typeof MainGruposRoute
  '/home': typeof MainHomeRoute
  '/perfil': typeof MainPerfilRoute
  '/ranking': typeof MainRankingRoute
  '/tabela': typeof MainTabelaRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/admin/apostas': typeof MainAdminApostasRoute
  '/admin/auditoria': typeof MainAdminAuditoriaRoute
  '/admin/checklist': typeof MainAdminChecklistRoute
  '/admin/configuracoes': typeof MainAdminConfiguracoesRoute
  '/admin/convites': typeof MainAdminConvitesRoute
  '/admin/custodia': typeof MainAdminCustodiaRoute
  '/admin/depositos': typeof MainAdminDepositosRoute
  '/admin/notificacoes': typeof MainAdminNotificacoesRoute
  '/admin/partidas': typeof MainAdminPartidasRoute
  '/admin/relatorios': typeof MainAdminRelatoriosRoute
  '/admin/saques': typeof MainAdminSaquesRoute
  '/admin/sync': typeof MainAdminSyncRoute
  '/admin/usuarios': typeof MainAdminUsuariosRouteWithChildren
  '/admin/': typeof MainAdminIndexRoute
  '/admin/usuarios/$id': typeof MainAdminUsuariosIdRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ajuda': typeof MainAjudaRoute
  '/carteira': typeof MainCarteiraRoute
  '/chaveamento': typeof MainChaveamentoRoute
  '/grupos': typeof MainGruposRoute
  '/home': typeof MainHomeRoute
  '/perfil': typeof MainPerfilRoute
  '/ranking': typeof MainRankingRoute
  '/tabela': typeof MainTabelaRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/admin/apostas': typeof MainAdminApostasRoute
  '/admin/auditoria': typeof MainAdminAuditoriaRoute
  '/admin/checklist': typeof MainAdminChecklistRoute
  '/admin/configuracoes': typeof MainAdminConfiguracoesRoute
  '/admin/convites': typeof MainAdminConvitesRoute
  '/admin/custodia': typeof MainAdminCustodiaRoute
  '/admin/depositos': typeof MainAdminDepositosRoute
  '/admin/notificacoes': typeof MainAdminNotificacoesRoute
  '/admin/partidas': typeof MainAdminPartidasRoute
  '/admin/relatorios': typeof MainAdminRelatoriosRoute
  '/admin/saques': typeof MainAdminSaquesRoute
  '/admin/sync': typeof MainAdminSyncRoute
  '/admin/usuarios': typeof MainAdminUsuariosRouteWithChildren
  '/admin': typeof MainAdminIndexRoute
  '/admin/usuarios/$id': typeof MainAdminUsuariosIdRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_main/admin': typeof MainAdminRouteWithChildren
  '/_main/ajuda': typeof MainAjudaRoute
  '/_main/carteira': typeof MainCarteiraRoute
  '/_main/chaveamento': typeof MainChaveamentoRoute
  '/_main/grupos': typeof MainGruposRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/perfil': typeof MainPerfilRoute
  '/_main/ranking': typeof MainRankingRoute
  '/_main/tabela': typeof MainTabelaRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/_main/admin/apostas': typeof MainAdminApostasRoute
  '/_main/admin/auditoria': typeof MainAdminAuditoriaRoute
  '/_main/admin/checklist': typeof MainAdminChecklistRoute
  '/_main/admin/configuracoes': typeof MainAdminConfiguracoesRoute
  '/_main/admin/convites': typeof MainAdminConvitesRoute
  '/_main/admin/custodia': typeof MainAdminCustodiaRoute
  '/_main/admin/depositos': typeof MainAdminDepositosRoute
  '/_main/admin/notificacoes': typeof MainAdminNotificacoesRoute
  '/_main/admin/partidas': typeof MainAdminPartidasRoute
  '/_main/admin/relatorios': typeof MainAdminRelatoriosRoute
  '/_main/admin/saques': typeof MainAdminSaquesRoute
  '/_main/admin/sync': typeof MainAdminSyncRoute
  '/_main/admin/usuarios': typeof MainAdminUsuariosRouteWithChildren
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/admin/usuarios/$id': typeof MainAdminUsuariosIdRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/ajuda'
    | '/carteira'
    | '/chaveamento'
    | '/grupos'
    | '/home'
    | '/perfil'
    | '/ranking'
    | '/tabela'
    | '/api/sitemap.xml'
    | '/admin/apostas'
    | '/admin/auditoria'
    | '/admin/checklist'
    | '/admin/configuracoes'
    | '/admin/convites'
    | '/admin/custodia'
    | '/admin/depositos'
    | '/admin/notificacoes'
    | '/admin/partidas'
    | '/admin/relatorios'
    | '/admin/saques'
    | '/admin/sync'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/usuarios/$id'
    | '/api/public/hooks/sync-partidas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/ajuda'
    | '/carteira'
    | '/chaveamento'
    | '/grupos'
    | '/home'
    | '/perfil'
    | '/ranking'
    | '/tabela'
    | '/api/sitemap.xml'
    | '/admin/apostas'
    | '/admin/auditoria'
    | '/admin/checklist'
    | '/admin/configuracoes'
    | '/admin/convites'
    | '/admin/custodia'
    | '/admin/depositos'
    | '/admin/notificacoes'
    | '/admin/partidas'
    | '/admin/relatorios'
    | '/admin/saques'
    | '/admin/sync'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/usuarios/$id'
    | '/api/public/hooks/sync-partidas'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/_main/admin'
    | '/_main/ajuda'
    | '/_main/carteira'
    | '/_main/chaveamento'
    | '/_main/grupos'
    | '/_main/home'
    | '/_main/perfil'
    | '/_main/ranking'
    | '/_main/tabela'
    | '/api/sitemap.xml'
    | '/_main/admin/apostas'
    | '/_main/admin/auditoria'
    | '/_main/admin/checklist'
    | '/_main/admin/configuracoes'
    | '/_main/admin/convites'
    | '/_main/admin/custodia'
    | '/_main/admin/depositos'
    | '/_main/admin/notificacoes'
    | '/_main/admin/partidas'
    | '/_main/admin/relatorios'
    | '/_main/admin/saques'
    | '/_main/admin/sync'
    | '/_main/admin/usuarios'
    | '/_main/admin/'
    | '/_main/admin/usuarios/$id'
    | '/api/public/hooks/sync-partidas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  ApiPublicHooksSyncPartidasRoute: typeof ApiPublicHooksSyncPartidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/tabela': {
      id: '/_main/tabela'
      path: '/tabela'
      fullPath: '/tabela'
      preLoaderRoute: typeof MainTabelaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ranking': {
      id: '/_main/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof MainRankingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/perfil': {
      id: '/_main/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof MainPerfilRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/grupos': {
      id: '/_main/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof MainGruposRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/chaveamento': {
      id: '/_main/chaveamento'
      path: '/chaveamento'
      fullPath: '/chaveamento'
      preLoaderRoute: typeof MainChaveamentoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/carteira': {
      id: '/_main/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof MainCarteiraRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ajuda': {
      id: '/_main/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof MainAjudaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/usuarios': {
      id: '/_main/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof MainAdminUsuariosRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/sync': {
      id: '/_main/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof MainAdminSyncRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/saques': {
      id: '/_main/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof MainAdminSaquesRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/relatorios': {
      id: '/_main/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof MainAdminRelatoriosRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/partidas': {
      id: '/_main/admin/partidas'
      path: '/partidas'
      fullPath: '/admin/partidas'
      preLoaderRoute: typeof MainAdminPartidasRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/notificacoes': {
      id: '/_main/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof MainAdminNotificacoesRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/depositos': {
      id: '/_main/admin/depositos'
      path: '/depositos'
      fullPath: '/admin/depositos'
      preLoaderRoute: typeof MainAdminDepositosRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/custodia': {
      id: '/_main/admin/custodia'
      path: '/custodia'
      fullPath: '/admin/custodia'
      preLoaderRoute: typeof MainAdminCustodiaRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/convites': {
      id: '/_main/admin/convites'
      path: '/convites'
      fullPath: '/admin/convites'
      preLoaderRoute: typeof MainAdminConvitesRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/configuracoes': {
      id: '/_main/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof MainAdminConfiguracoesRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/checklist': {
      id: '/_main/admin/checklist'
      path: '/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof MainAdminChecklistRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/auditoria': {
      id: '/_main/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof MainAdminAuditoriaRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/apostas': {
      id: '/_main/admin/apostas'
      path: '/apostas'
      fullPath: '/admin/apostas'
      preLoaderRoute: typeof MainAdminApostasRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/api/public/hooks/sync-partidas': {
      id: '/api/public/hooks/sync-partidas'
      path: '/api/public/hooks/sync-partidas'
      fullPath: '/api/public/hooks/sync-partidas'
      preLoaderRoute: typeof ApiPublicHooksSyncPartidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/admin/usuarios/$id': {
      id: '/_main/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof MainAdminUsuariosIdRouteImport
      parentRoute: typeof MainAdminUsuariosRoute
    }
  }
}

interface MainAdminUsuariosRouteChildren {
  MainAdminUsuariosIdRoute: typeof MainAdminUsuariosIdRoute
}

const MainAdminUsuariosRouteChildren: MainAdminUsuariosRouteChildren = {
  MainAdminUsuariosIdRoute: MainAdminUsuariosIdRoute,
}

const MainAdminUsuariosRouteWithChildren =
  MainAdminUsuariosRoute._addFileChildren(MainAdminUsuariosRouteChildren)

interface MainAdminRouteChildren {
  MainAdminApostasRoute: typeof MainAdminApostasRoute
  MainAdminAuditoriaRoute: typeof MainAdminAuditoriaRoute
  MainAdminChecklistRoute: typeof MainAdminChecklistRoute
  MainAdminConfiguracoesRoute: typeof MainAdminConfiguracoesRoute
  MainAdminConvitesRoute: typeof MainAdminConvitesRoute
  MainAdminCustodiaRoute: typeof MainAdminCustodiaRoute
  MainAdminDepositosRoute: typeof MainAdminDepositosRoute
  MainAdminNotificacoesRoute: typeof MainAdminNotificacoesRoute
  MainAdminPartidasRoute: typeof MainAdminPartidasRoute
  MainAdminRelatoriosRoute: typeof MainAdminRelatoriosRoute
  MainAdminSaquesRoute: typeof MainAdminSaquesRoute
  MainAdminSyncRoute: typeof MainAdminSyncRoute
  MainAdminUsuariosRoute: typeof MainAdminUsuariosRouteWithChildren
  MainAdminIndexRoute: typeof MainAdminIndexRoute
}

const MainAdminRouteChildren: MainAdminRouteChildren = {
  MainAdminApostasRoute: MainAdminApostasRoute,
  MainAdminAuditoriaRoute: MainAdminAuditoriaRoute,
  MainAdminChecklistRoute: MainAdminChecklistRoute,
  MainAdminConfiguracoesRoute: MainAdminConfiguracoesRoute,
  MainAdminConvitesRoute: MainAdminConvitesRoute,
  MainAdminCustodiaRoute: MainAdminCustodiaRoute,
  MainAdminDepositosRoute: MainAdminDepositosRoute,
  MainAdminNotificacoesRoute: MainAdminNotificacoesRoute,
  MainAdminPartidasRoute: MainAdminPartidasRoute,
  MainAdminRelatoriosRoute: MainAdminRelatoriosRoute,
  MainAdminSaquesRoute: MainAdminSaquesRoute,
  MainAdminSyncRoute: MainAdminSyncRoute,
  MainAdminUsuariosRoute: MainAdminUsuariosRouteWithChildren,
  MainAdminIndexRoute: MainAdminIndexRoute,
}

const MainAdminRouteWithChildren = MainAdminRoute._addFileChildren(
  MainAdminRouteChildren,
)

interface MainRouteChildren {
  MainAdminRoute: typeof MainAdminRouteWithChildren
  MainAjudaRoute: typeof MainAjudaRoute
  MainCarteiraRoute: typeof MainCarteiraRoute
  MainChaveamentoRoute: typeof MainChaveamentoRoute
  MainGruposRoute: typeof MainGruposRoute
  MainHomeRoute: typeof MainHomeRoute
  MainPerfilRoute: typeof MainPerfilRoute
  MainRankingRoute: typeof MainRankingRoute
  MainTabelaRoute: typeof MainTabelaRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAdminRoute: MainAdminRouteWithChildren,
  MainAjudaRoute: MainAjudaRoute,
  MainCarteiraRoute: MainCarteiraRoute,
  MainChaveamentoRoute: MainChaveamentoRoute,
  MainGruposRoute: MainGruposRoute,
  MainHomeRoute: MainHomeRoute,
  MainPerfilRoute: MainPerfilRoute,
  MainRankingRoute: MainRankingRoute,
  MainTabelaRoute: MainTabelaRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  ApiPublicHooksSyncPartidasRoute: ApiPublicHooksSyncPartidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
