/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainRankingRouteImport } from './routes/_main/ranking'
import { Route as MainPerfilRouteImport } from './routes/_main/perfil'
import { Route as MainHomeRouteImport } from './routes/_main/home'
import { Route as MainGruposRouteImport } from './routes/_main/grupos'
import { Route as MainChaveamentoRouteImport } from './routes/_main/chaveamento'
import { Route as MainCarteiraRouteImport } from './routes/_main/carteira'
import { Route as MainAdminRouteImport } from './routes/_main/admin'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin.index'
import { Route as MainAdminPartidasRouteImport } from './routes/_main/admin.partidas'
import { Route as ApiPublicHooksSyncPartidasRouteImport } from './routes/api/public/hooks/sync-partidas'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRankingRoute = MainRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => MainRoute,
} as any)
const MainPerfilRoute = MainPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainGruposRoute = MainGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => MainRoute,
} as any)
const MainChaveamentoRoute = MainChaveamentoRouteImport.update({
  id: '/chaveamento',
  path: '/chaveamento',
  getParentRoute: () => MainRoute,
} as any)
const MainCarteiraRoute = MainCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminPartidasRoute = MainAdminPartidasRouteImport.update({
  id: '/partidas',
  path: '/partidas',
  getParentRoute: () => MainAdminRoute,
} as any)
const ApiPublicHooksSyncPartidasRoute =
  ApiPublicHooksSyncPartidasRouteImport.update({
    id: '/api/public/hooks/sync-partidas',
    path: '/api/public/hooks/sync-partidas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof MainAdminRouteWithChildren
  '/carteira': typeof MainCarteiraRoute
  '/chaveamento': typeof MainChaveamentoRoute
  '/grupos': typeof MainGruposRoute
  '/home': typeof MainHomeRoute
  '/perfil': typeof MainPerfilRoute
  '/ranking': typeof MainRankingRoute
  '/admin/partidas': typeof MainAdminPartidasRoute
  '/admin/': typeof MainAdminIndexRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/carteira': typeof MainCarteiraRoute
  '/chaveamento': typeof MainChaveamentoRoute
  '/grupos': typeof MainGruposRoute
  '/home': typeof MainHomeRoute
  '/perfil': typeof MainPerfilRoute
  '/ranking': typeof MainRankingRoute
  '/admin/partidas': typeof MainAdminPartidasRoute
  '/admin': typeof MainAdminIndexRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_main/admin': typeof MainAdminRouteWithChildren
  '/_main/carteira': typeof MainCarteiraRoute
  '/_main/chaveamento': typeof MainChaveamentoRoute
  '/_main/grupos': typeof MainGruposRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/perfil': typeof MainPerfilRoute
  '/_main/ranking': typeof MainRankingRoute
  '/_main/admin/partidas': typeof MainAdminPartidasRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/api/public/hooks/sync-partidas': typeof ApiPublicHooksSyncPartidasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/carteira'
    | '/chaveamento'
    | '/grupos'
    | '/home'
    | '/perfil'
    | '/ranking'
    | '/admin/partidas'
    | '/admin/'
    | '/api/public/hooks/sync-partidas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/carteira'
    | '/chaveamento'
    | '/grupos'
    | '/home'
    | '/perfil'
    | '/ranking'
    | '/admin/partidas'
    | '/admin'
    | '/api/public/hooks/sync-partidas'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/login'
    | '/onboarding'
    | '/_main/admin'
    | '/_main/carteira'
    | '/_main/chaveamento'
    | '/_main/grupos'
    | '/_main/home'
    | '/_main/perfil'
    | '/_main/ranking'
    | '/_main/admin/partidas'
    | '/_main/admin/'
    | '/api/public/hooks/sync-partidas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicHooksSyncPartidasRoute: typeof ApiPublicHooksSyncPartidasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/ranking': {
      id: '/_main/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof MainRankingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/perfil': {
      id: '/_main/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof MainPerfilRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/grupos': {
      id: '/_main/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof MainGruposRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/chaveamento': {
      id: '/_main/chaveamento'
      path: '/chaveamento'
      fullPath: '/chaveamento'
      preLoaderRoute: typeof MainChaveamentoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/carteira': {
      id: '/_main/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof MainCarteiraRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/partidas': {
      id: '/_main/admin/partidas'
      path: '/partidas'
      fullPath: '/admin/partidas'
      preLoaderRoute: typeof MainAdminPartidasRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/api/public/hooks/sync-partidas': {
      id: '/api/public/hooks/sync-partidas'
      path: '/api/public/hooks/sync-partidas'
      fullPath: '/api/public/hooks/sync-partidas'
      preLoaderRoute: typeof ApiPublicHooksSyncPartidasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainAdminRouteChildren {
  MainAdminPartidasRoute: typeof MainAdminPartidasRoute
  MainAdminIndexRoute: typeof MainAdminIndexRoute
}

const MainAdminRouteChildren: MainAdminRouteChildren = {
  MainAdminPartidasRoute: MainAdminPartidasRoute,
  MainAdminIndexRoute: MainAdminIndexRoute,
}

const MainAdminRouteWithChildren = MainAdminRoute._addFileChildren(
  MainAdminRouteChildren,
)

interface MainRouteChildren {
  MainAdminRoute: typeof MainAdminRouteWithChildren
  MainCarteiraRoute: typeof MainCarteiraRoute
  MainChaveamentoRoute: typeof MainChaveamentoRoute
  MainGruposRoute: typeof MainGruposRoute
  MainHomeRoute: typeof MainHomeRoute
  MainPerfilRoute: typeof MainPerfilRoute
  MainRankingRoute: typeof MainRankingRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAdminRoute: MainAdminRouteWithChildren,
  MainCarteiraRoute: MainCarteiraRoute,
  MainChaveamentoRoute: MainChaveamentoRoute,
  MainGruposRoute: MainGruposRoute,
  MainHomeRoute: MainHomeRoute,
  MainPerfilRoute: MainPerfilRoute,
  MainRankingRoute: MainRankingRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicHooksSyncPartidasRoute: ApiPublicHooksSyncPartidasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
